### ISSUE TITLE
Add table steampipecloud_workspace_database_log

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-steampipecloud#20]
I'd like to query the database log entries for a workspace using the steampipecloud plugin!

Here are the APIs in question:
```
/org/{org_handle}/workspace/{workspace_handle}/logs
/user/{user_handle}/workspace/{workspace_handle}/logs
```

**Comment by cbruno10** [comment]
Added in https://github.com/turbot/steampipe-plugin-steampipecloud/commit/6df7e81e819219017728cc4851c6599b86e8f19b.
