### ISSUE TITLE
Workspace connection table should include object fields (connection, created_by)

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-steampipecloud#21]
The workspace connection API returns object data for both the connection and the created_by fields, but these objects are not currently returned as columns in the plugin.

Could we please add the object columns in this table (and perhaps others) as appropriate?

**Comment by cbruno10** [comment]
Added in https://github.com/turbot/steampipe-plugin-steampipecloud/commit/67065315a64ca178494214d125e360f11fd17a13
